spring:
  application:
    name: meuaps
  data:
    mongodb:
      uri: mongodb://localhost:27017
#      authentication-database: admin
#      host: localhost
#      port: 27017
      database: loteria
#      username: admin
#      password: admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /api-docs
  version: @springdoc.version@

server:
  port: 8080

loteria:
  megasena:
#    tamanho-thread: 10
    tamanho-thread: 100000
#    quantidade-jogos: 100
    quantidade-jogos: 15403141
  dupla:
    tamanho-thread: 10
    quantidade-jogos: 100
  lotofacil:
    tamanho-thread: 10
    quantidade-jogos: 100